# Generated by Django 3.2.19 on 2023-07-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('qty', models.IntegerField(max_length=10)),
                ('image', models.ImageField(upload_to='product/')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
