# Generated by Django 3.2.19 on 2023-07-05 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230705_1125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_tb1',
            new_name='product_tb',
        ),
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_tb')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_register_tb')),
            ],
        ),
    ]
