# Generated by Django 3.2.19 on 2023-07-04 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ad_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad_cart1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=255)),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.u_reg')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ad_product')),
            ],
        ),
        migrations.DeleteModel(
            name='ad_cart',
        ),
    ]
