# Generated by Django 3.2.19 on 2023-07-04 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230704_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ad_cart1',
            new_name='ad_cart',
        ),
    ]
