# Generated by Django 3.2.19 on 2023-07-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_ad_cart1_ad_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad_cart',
            old_name='num',
            new_name='uid',
        ),
    ]
