# Generated by Django 3.2.19 on 2023-07-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230704_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad_cart',
            name='quantity',
        ),
    ]
