# Generated by Django 3.2.19 on 2023-07-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_ad_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_cart',
            name='quantity',
            field=models.IntegerField(default=1, max_length=255),
        ),
    ]
